OIDC Compatible
exporo/actions-serverless pull request #4
Opened 2023-05-23 06:31 UTC by teja-srinivas

make the action to use OIDC
as the OIDC uses 3 values AWS_ACCESS_KEY, AWS_SECRET_KEY, AWS_SESSION_TOKEN

2023-05-23 10:03 UTC, miguelnv requested changes
Hi @teja-srinivas, you must also add the session token in [action.yml](https://github.com/exporo/actions-serverless/blob/master/action.yml) since it will be passed to docker image through this action run

2023-05-23 10:49 UTC, robertpranjic approved these changes

2023-05-25 17:23 UTC, miguelnv approved these changes

2023-05-25 17:23 UTC, afonsobarros approved these changes

2023-05-25 17:25 UTC, merged